import type { SiteContent } from "./types";

/** 힐링로드 ON 오디오 원본 위치(treter.kr). 관리자에서 각 항목의 오디오를 새로 올리면 그 주소로 바뀝니다. */
const HEALING_AUDIO_BASE = "https://treter.kr/healingroad/manager/upload_mp3/";
const wav = (filename: string) => HEALING_AUDIO_BASE + encodeURIComponent(filename);

/**
 * 기본 콘텐츠 (기획서 원고 기준).
 * 관리자에서 저장한 값은 `content/site-content.json` 에 쌓이고, 저장되지 않은 키는 여기 값이 쓰입니다.
 * 새 필드를 추가할 때는 여기에도 기본값을 넣어야 기존 저장본과 합쳐집니다.
 */
export const DEFAULT_CONTENT: SiteContent = {
  site: {
    name: "㈜위드더레이크",
    nameEn: "WITH THE LAKE",
    description:
      "㈜위드더레이크는 데이터와 건강행동을 연결해 시니어의 건강한 자립생활이 더 오래 지속되도록 돕는 지역사회 기반 예방건강관리 기업입니다.",
    tagline: "건강한 삶은 병원 밖, 일상에서 시작됩니다",
    contact: {
      team: "서비스기획팀",
      person: "김민주 과장",
      phone: "010-4629-5925",
      email: "contact@withthelake.com",
      address: "강원특별자치도 춘천시 후석로462번길 7, 춘천 ICT혁신센터 206호",
      postalCode: "24232",
    },
    links: {
      store: "https://smartstore.naver.com/withlab201",
      appIos: "",
      appAndroid: "",
      menbalooIos: "https://apps.apple.com/kr/app/%EB%A7%A8%EB%B0%9C%EB%A3%A8/id6651824430",
      menbalooAndroid: "https://play.google.com/store/apps/details?id=com.apppp.menbaloo",
      cafe: "https://cafe.naver.com/healingroadon",
      blog: "https://blog.naver.com/with_thelake",
      instagram: "https://www.instagram.com/withwellme/",
      youtube: "https://www.youtube.com/channel/UC8vmE6swgfF-PvsVIQUmsOQ",
    },
    heroVideo: "",
    heroPoster: "/assets/stock/barefoot-stream.jpg",
    publish: { withWellMe: true, communityHealth: true },
  },

  home: {
    intro: {
      slogan: "Good life, good people",
      headline: "건강한 삶은 병원 밖,\n일상에서 시작됩니다",
      lead: "㈜위드더레이크는 데이터와 건강행동을 연결해 시니어의 건강한 자립생활을 돕는 지역사회 기반 예방건강관리 기업입니다.",
      primaryCta: { label: "사업·협력 문의", href: "/contact" },
      secondaryCta: { label: "위드더레이크 알아보기", href: "/about" },
    },
    beginning: {
      eyebrow: "Our Beginning",
      headline: "우리는 함께 걷는\n현장에서 시작했습니다",
      lead: "㈜위드더레이크는 지역사회 시니어 건강 현장에서 출발한 예방건강관리 기업입니다.",
      image: "/assets/activities/barefoot-3.jpg",
      imageAlt: "맨발걷기 프로그램 참가자들이 둥글게 모여 발을 맞댄 모습",
      steps: [
        { no: "01", title: "함께 걷는 현장", body: "건강한 습관을 이어가도 그 변화를 확인할 방법이 없다는 것이 현장의 과제였습니다." },
        { no: "02", title: "확인할 수 있는 변화", body: "기술과 데이터는 그 변화를 확인하고 지속하게 하는 도구입니다." },
        { no: "03", title: "스스로 돌보는 건강", body: "누구나 자신의 건강을 스스로 돌볼 기회를 가져야 한다는 원칙에서 사업을 설계합니다." },
      ],
    },
    problem: {
      bannerImage: "/assets/activities/barefoot-2.jpg",
      bannerAlt: "지역 주민과 함께 숲길을 걷는 맨발걷기 프로그램",
      bannerEn: "Health in Daily Life",
      bannerKo: "병원 밖, 일상에서 시작하는 예방건강관리",
      title: "건강관리는 왜 지속되기 어려울까요?",
      cards: [
        { title: "알아도 지속하기 어렵다", body: "건강에 좋은 것은 이미 알고 있습니다. 하지만 변화가 눈에 보이지 않으면 행동은 오래 이어지지 않습니다." },
        { title: "데이터가 흩어져 있다", body: "생체 정보, 걷기, 운동, 생활 습관이 각각 다른 곳에 남습니다. 하나로 이어지지 않으면 의미를 읽을 수 없습니다." },
        { title: "기관이 개인별로 관리하기 어렵다", body: "담당자 한 사람이 여러 사람을 돌봅니다. 개인별 건강 변화를 지속적으로 기록하고 추적할 수단이 필요합니다." },
      ],
      quote: "건강정보를 제공하는 것에서 끝나지 않고, 측정 → 이해 → 건강행동 → 지속 → 변화 확인까지 연결되는 예방건강관리 구조를 만들어갑니다.",
    },
    howWeWork: {
      eyebrow: "How We Work",
      title: "건강정보를 제공하는 것에서 끝내지 않습니다",
      lead: "측정에서 변화 확인까지 다섯 단계가 하나로 이어지고, 확인된 변화는 다시 측정으로 돌아옵니다.",
      centerLabel: "CLOSED LOOP",
      centerText: "확인이 다음 행동의\n이유가 되는 순환",
      steps: [
        { n: "01", title: "측정", en: "Measure", icon: "measure", body: "소변 기반 생체데이터와 걷기·운동 등 생활데이터를 일상에서 확인합니다" },
        { n: "02", title: "이해", en: "Understand", icon: "understand", body: "숫자를 쉬운 언어로 바꿔, 지금 내 상태가 어떤 의미인지 알려줍니다" },
        { n: "03", title: "행동", en: "Act", icon: "walk", body: "상태에 맞는 건강 루틴과 프로그램으로 다음 행동을 제안합니다" },
        { n: "04", title: "지속", en: "Continue", icon: "continue", body: "기록이 쌓이고 리마인드가 이어져 습관이 유지됩니다" },
        { n: "05", title: "변화 확인", en: "Confirm", icon: "trend", body: "다시 측정해 나아졌는지 확인하고, 그 변화가 다음 행동의 이유가 됩니다" },
      ],
    },
    whatWeDo: {
      panelTitle: "What We Do",
      title: "세 가지 방식으로 건강을 연결합니다",
      lead: "기술·데이터·웰니스·지역사회를 하나의 흐름으로 연결해, 시니어가 자신의 건강을 이해하고 건강한 행동을 지속하도록 돕습니다.",
      businesses: [
        {
          key: "senio",
          name: "SENIO",
          kind: "디지털 헬스케어",
          tag: "건강을 이해하는 기술",
          body: "소변 기반 생체데이터와 걷기·운동 등 생활데이터를 연결하는 디지털 헬스케어 솔루션입니다. 비의료 인력도 3분 안에 7종 지표를 측정하고 기록할 수 있습니다.",
          pills: ["Strip", "Lens", "Care"],
          image: "/assets/senio/device-styled.jpg",
          imageAlt: "SENIO 앱과 측정기",
          href: "/senio",
          actions: [
            { label: "자세히 보기", href: "/senio", variant: "primary" },
            { label: "실증·협력 문의", href: "/contact?type=senio", variant: "secondary" },
          ],
        },
        {
          key: "withWellMe",
          name: "WITH WELL ME",
          kind: "웰니스 브랜드",
          tag: "건강한 행동을 일상으로",
          body: "걷기, 운동, 건강 루틴, 콘텐츠, 셀프케어 제품을 통해 건강한 생활습관이 지속되도록 돕는 웰니스 브랜드입니다.",
          pills: ["EAT", "MOVE", "WALK", "CARE", "RECOVER"],
          image: "/assets/stock/barefoot-trail.jpg",
          imageAlt: "숲길을 맨발로 걷는 모습",
          href: "/what-we-do/with-well-me",
          actions: [
            { label: "스토어 바로가기", href: "https://smartstore.naver.com/withlab201", variant: "primary", external: true },
            { label: "자세히 보기", href: "/what-we-do/with-well-me", variant: "secondary" },
          ],
        },
        {
          key: "communityHealth",
          name: "COMMUNITY HEALTH",
          kind: "오프라인 프로그램",
          tag: "현장에서 함께 만드는 예방건강관리",
          body: "지자체·복지기관·기업과 함께 걷기, 운동, 노쇠 예방, 생활습관, 마음건강 프로그램을 운영합니다.",
          pills: ["걷기", "운동", "노쇠 예방", "생활습관", "마음건강"],
          image: "/assets/activities/barefoot-7.jpg",
          imageAlt: "지역 주민과 함께하는 맨발걷기 프로그램",
          href: "/what-we-do/community-health",
          actions: [
            { label: "프로그램 문의", href: "/contact?type=program", variant: "primary" },
            { label: "자세히 보기", href: "/what-we-do/community-health", variant: "secondary" },
          ],
        },
      ],
    },
    senio: {
      eyebrow: "SENIO",
      sub: "Senior Preventive Health Solution · Made by WITH THE LAKE",
      title: "건강관리, 확인할 수 있으면 습관이 될 수 있습니다.",
      body: "스트립을 측정기에 넣으면 3분 안에 7종 지표가 네 단계로 표시되고, 그 기록은 앱과 기관 대시보드에 자동으로 쌓입니다.",
      stats: [
        { value: "7종", label: "한 번에 확인하는 지표" },
        { value: "3분", label: "측정부터 결과 확인까지" },
        { value: "4단계", label: "좋음 · 적절 · 주의 · 위험" },
      ],
      image: "/assets/senio/device-screen-1.png",
      imageAlt: "SENIO Lens 측정기 화면: 당뇨·간·신장 기능 결과가 네 단계로 표시된다",
      primaryCta: { label: "SENIO 자세히 보기", href: "/senio" },
      secondaryCta: { label: "실증 · 도입 문의", href: "/contact?type=senio" },
    },
    partners: {
      title: "Our Partners",
      lead: "업무협약을 맺은 기관, 인증과 수상, 선정 사업을 사실 그대로 기록합니다.",
      ctaLabel: "전체 성과 보기",
    },
    story: { title: "Story", lead: "현장에서 만드는 건강한 변화", moreLabel: "STORY 전체 보기" },
    forOrganizations: {
      title: "For Organizations",
      statement: "한 사람의 건강부터\n지역사회의 건강까지",
      lead: "기관의 목적과 운영 방식에 맞춰 프로그램과 SENIO 도입 구성을 조정합니다.",
      cardEyebrow: "For Organizations",
      cardTitle: "기관과 함께 설계하는\n지역사회 예방건강관리",
      targets: [
        { icon: "building", audience: "지자체 · 공공기관", headline: "지역사회 예방건강관리", body: "통합돌봄 사업과 연계한 주민 건강관리 프로그램" },
        { icon: "care", audience: "복지 · 시니어 기관", headline: "시니어 건강 프로그램과 SENIO", body: "이용자 건강 모니터링과 담당자 업무 효율화" },
        { icon: "badge", audience: "기업 · 금융기관", headline: "ESG·사회공헌 건강사업", body: "지역사회 기여와 연결되는 건강 프로그램 설계" },
        { icon: "home", audience: "웰니스 · 시니어 주거", headline: "건강관리와 웰니스 프로그램", body: "입주자 대상 건강관리 서비스" },
      ],
      ctaTitle: "더 건강한 일상을, 더 많은 사람에게",
      ctaBody: "사업·협력, SENIO 실증·도입, 프로그램 운영에 관한 문의를 남겨 주시면 담당자가 확인 후 연락드립니다.",
      primaryCta: { label: "사업·협력 문의", href: "/contact" },
      secondaryCta: { label: "SENIO 실증·도입 문의", href: "/contact?type=senio" },
    },
  },

  about: {
    meta: {
      title: "ABOUT — 회사소개",
      description: "㈜위드더레이크는 데이터와 건강행동을 연결해 시니어의 건강한 자립생활이 더 오래 지속되도록 돕는 지역사회 기반 예방건강관리 기업입니다.",
    },
    header: {
      eyebrow: "About Us",
      title: "회사소개",
      lead: "㈜위드더레이크는 데이터와 건강행동을 연결해 시니어의 건강한 자립생활이 더 오래 지속되도록 돕는 지역사회 기반 예방건강관리 기업입니다. 병원 밖 일상에서 건강을 측정하고 이해하고 행동으로 잇는 구조를 만듭니다.",
      image: "/assets/stock/senior-care-visit.jpg",
      imageAlt: "시니어 부부와 상담하는 건강관리 담당자",
    },
    perception: {
      eyebrow: "우리가 전하려는 인식",
      title: "맨발걷기, 제품, 프로그램, SENIO를 각각 하는 회사가 아니라",
      leadBefore: "시니어가 자신의 건강을 이해하고 건강한 행동을 지속하도록",
      leadHighlight: "기술·데이터·웰니스·지역사회를 연결하는 회사",
      leadAfter: "입니다.",
    },
    message: {
      eyebrow: "핵심 메시지",
      title: "건강한 삶은 병원 밖, 일상에서 시작됩니다.",
      body: "건강정보를 제공하는 것에서 끝나지 않고, 측정 → 이해 → 건강행동 → 지속 → 변화 확인까지 연결되는 예방건강관리 구조를 만들어갑니다.",
      steps: ["측정", "이해", "행동", "지속", "변화 확인"],
    },
    identity: {
      eyebrow: "Identity",
      lead: "따뜻하지만 전문적이고, 자연친화적이지만 기술적이며, 사회적 가치를 추구하면서도 사업성이 있는 기업으로 나아갑니다.",
      axes: [
        { key: "Nature", ko: "자연", body: "자연 · 걷기 · 위드더레이크의 시작", image: "/assets/stock/barefoot-trail.jpg", alt: "숲길을 맨발로 걷는 모습" },
        { key: "Human", ko: "사람", body: "시니어 · 현장 · 커뮤니티", image: "/assets/stock/senior-hands.jpg", alt: "시니어의 손을 맞잡은 돌봄 현장" },
        { key: "Science", ko: "과학", body: "SENIO · 데이터 · R&D", image: "/assets/senio/device-styled.jpg", alt: "SENIO 앱 측정 결과 화면" },
      ],
    },
    businesses: {
      eyebrow: "사업 구성",
      title: "현재 세 개의 사업을 운영합니다",
      items: [
        { key: "senio", name: "SENIO", kind: "디지털 헬스케어", desc: "소변 기반 생체데이터와 걷기·운동 등 생활데이터를 연결해 건강 상태를 확인하는 솔루션", href: "/senio" },
        { key: "withWellMe", name: "WITH WELL ME", kind: "웰니스 브랜드", desc: "강원도 자연원료 기반 셀프케어 제품과 건강 루틴·콘텐츠", href: "/what-we-do/with-well-me" },
        { key: "communityHealth", name: "COMMUNITY HEALTH", kind: "오프라인 프로그램", desc: "지자체·복지기관·기업과 함께 운영하는 예방건강관리 프로그램", href: "/what-we-do/community-health" },
      ],
    },
    info: { certsEyebrow: "인증", infoEyebrow: "회사 정보", ctaLabel: "사업·협력 문의하기" },
  },

  whatWeDo: {
    meta: {
      title: "WHAT WE DO — SENIO · WITH WELL ME · COMMUNITY HEALTH",
      description: "세 가지 방식으로 건강을 연결합니다. SENIO(디지털 헬스케어), WITH WELL ME(웰니스 브랜드), COMMUNITY HEALTH(오프라인 프로그램).",
    },
    header: {
      eyebrow: "What We Do",
      title: "사업소개",
      lead: "세 가지 방식으로 건강을 연결합니다. 기술(SENIO), 웰니스(WITH WELL ME), 지역사회 프로그램(COMMUNITY HEALTH)이 측정 → 이해 → 행동 → 지속 → 변화 확인의 순환 안에서 하나로 이어집니다.",
    },
  },

  withWellMe: {
    meta: {
      title: "WITH WELL ME — 웰니스 브랜드",
      description: "강원도 자연원료 기반 셀프케어 제품과 건강 루틴·콘텐츠로 건강한 생활습관이 지속되도록 돕는 웰니스 브랜드입니다.",
    },
    header: {
      eyebrow: "With Well Me",
      title: "위드웰미",
      lead: "건강한 행동을 일상으로. 걷기, 운동, 건강 루틴, 콘텐츠, 셀프케어 제품을 통해 건강한 생활습관이 지속되도록 돕는 웰니스 브랜드입니다. 강원도 자연원료 기반 셀프케어 제품과 건강 루틴·콘텐츠를 준비하고 있습니다.",
      image: "/assets/stock/barefoot-trail.jpg",
      imageAlt: "숲길을 맨발로 걷는 모습",
      logo: "/assets/logo/with-well-me.png",
    },
    axes: {
      eyebrow: "5 Axes",
      title: "다섯 가지 축으로 건강한 하루를 설계합니다",
      lead: "먹고, 움직이고, 걷고, 돌보고, 회복하는 하루의 리듬을 제품과 콘텐츠로 뒷받침합니다.",
      items: [
        { name: "EAT", ko: "먹기", desc: "강원도 자연원료 기반 식품과 식습관 루틴" },
        { name: "MOVE", ko: "움직이기", desc: "일상에서 이어가는 운동 루틴과 콘텐츠" },
        { name: "WALK", ko: "걷기", desc: "맨발걷기에서 시작한 걷기 습관과 프로그램" },
        { name: "CARE", ko: "돌보기", desc: "몸 상태를 확인하고 돌보는 셀프케어 제품" },
        { name: "RECOVER", ko: "회복하기", desc: "휴식과 회복을 돕는 루틴과 제품" },
      ],
    },
    products: {
      eyebrow: "Products",
      title: "제품 소개",
      lead: "위드웰미 풋케어 제품과 어싱 제품, 힐링로드ON 걷기 체험을 네이버 스마트스토어에서 구매하실 수 있습니다.",
      note: "WITH WELL ME 제품은 네이버 스마트스토어에서 만나보실 수 있습니다.",
      ctaLabel: "스토어 바로가기",
    },
  },

  communityHealth: {
    meta: {
      title: "COMMUNITY HEALTH — 지역사회 예방건강관리 프로그램",
      description: "지자체·복지기관·기업과 함께 걷기, 운동, 노쇠 예방, 생활습관, 마음건강 프로그램을 운영합니다.",
    },
    header: {
      eyebrow: "Community Health",
      title: "건강 프로그램",
      lead: "현장에서 함께 만드는 예방건강관리. 지자체·복지기관·기업과 함께 걷기, 운동, 노쇠 예방, 생활습관, 마음건강 프로그램을 운영합니다. 프로그램에서 쌓인 기록은 SENIO와 연결되어 변화를 확인하는 근거가 됩니다.",
      image: "/assets/activities/barefoot-2.jpg",
      imageAlt: "지역 주민과 함께하는 맨발걷기 프로그램",
      ctaLabel: "프로그램 문의",
    },
    programs: {
      eyebrow: "Programs",
      title: "프로그램 소개",
      lead: "기관의 목적과 이용자 특성에 맞춰 다섯 가지 주제를 조합해 운영합니다.",
      items: [
        { name: "걷기", body: "맨발걷기를 중심으로 한 지역 걷기 프로그램. 힐링로드ON에서 시작했습니다." },
        { name: "운동", body: "시니어의 체력과 균형을 유지하는 생활 운동 프로그램." },
        { name: "노쇠 예방", body: "근력·영양·활동량을 함께 관리해 노쇠를 늦추는 프로그램." },
        { name: "생활습관", body: "식사·수면·활동 기록으로 습관의 변화를 확인하는 프로그램." },
        { name: "마음건강", body: "함께 걷고 대화하며 외로움과 스트레스를 줄이는 프로그램." },
      ],
    },
    healingRoad: {
      eyebrow: "힐링로드ON",
      title: "맨발로 함께 걷는 지역 건강걷기 프로그램",
      lead: "위드더레이크의 시작점입니다. 지역 주민이 함께 흙길을 걷고, 지도자 양성과정을 거친 건강리더가 프로그램을 이끕니다.",
      walkTitle: "함께 걷기",
      walkBody: "맨발걷기 앱 ‘맨발루’로 걷기 기록을 남기고, 네이버 카페 힐링로드ON에서 지역 걷기 모임 소식을 확인하세요.",
      photos: ["/assets/activities/barefoot-1.jpg", "/assets/activities/barefoot-6.jpg", "/assets/activities/barefoot-7.jpg", "/assets/activities/barefoot-4.jpg"],
    },
    cases: {
      eyebrow: "Cases",
      title: "운영 사례",
      lead: "업무협약을 맺은 기관과 함께 프로그램을 운영하고 있습니다. 상세 사례는 확정되는 대로 추가됩니다.",
      storiesTitle: "힐링로드ON 이야기",
      moreLabel: "더 보기",
    },
    cta: {
      title: "프로그램 도입과 운영을 상담해 드립니다",
      body: "기관 유형, 이용자 규모, 운영 기간에 맞춰 프로그램을 구성합니다.",
      label: "프로그램 문의",
    },
  },

  senio: {
    meta: {
      title: "SENIO — 시니어 예방건강관리 솔루션",
      description: "세니오(SENIO)는 소변 기반 생체데이터와 걷기·운동 등 생활데이터를 연결하는 시니어 예방건강관리 솔루션입니다. 3분 안에 7종 지표를 네 단계로 확인합니다.",
    },
    hero: {
      eyebrow: "SENIO · Digital Healthcare",
      title: "건강관리, 확인할 수 있으면 습관이 될 수 있습니다.",
      lead: "세니오(SENIO)는 소변 기반 생체데이터와 걷기·운동 등 생활데이터를 연결하는 시니어 예방건강관리 솔루션입니다.",
      body: "스트립을 측정기에 넣으면 3분 안에 7종 지표가 네 단계로 표시되고, 그 기록은 앱과 기관 대시보드에 자동으로 쌓입니다. 한 번의 검사로 끝나지 않습니다. 결과를 이해할 수 있는 말로 바꾸고, 다음 행동으로 이어지게 하고, 그 변화를 다시 확인하는 것까지를 하나의 흐름으로 설계했습니다.",
      primaryCta: { label: "실증 · 도입 문의", href: "/contact?type=senio" },
      secondaryCta: { label: "측정 흐름 보기", href: "#senio-flow" },
      stats: [
        { value: "7종", label: "한 번에 확인하는 지표" },
        { value: "3분", label: "측정부터 결과 확인까지" },
        { value: "4단계", label: "좋음 · 적절 · 주의 · 위험" },
      ],
      image: "/assets/senio/device-screen-1.png",
      imageAlt: "SENIO Lens 측정기 화면: 당뇨·간·신장 기능 결과가 위험·주의·좋음 네 단계로 표시된다",
    },
    flow: {
      eyebrow: "How It Works",
      title: "스트립 한 장, 3분이면 오늘의 상태를 확인합니다",
      lead: "측정 결과는 숫자 대신 네 단계 색으로 표시되어 시니어도 담당자도 한눈에 이해할 수 있습니다.",
      steps: [
        { n: "01", icon: "strip", title: "스트립에 소변을 묻힙니다", body: "채혈 없이 한 장의 스트립으로 준비합니다. 비의료 인력도 어렵지 않게 진행할 수 있습니다." },
        { n: "02", icon: "device", title: "측정기에 넣고 3분을 기다립니다", body: "광학 센서가 스트립을 읽어 7종 지표를 좋음·적절·주의·위험 네 단계로 표시합니다." },
        { n: "03", icon: "dashboard", title: "앱과 대시보드에 기록이 쌓입니다", body: "결과는 자동으로 앱과 기관 대시보드에 저장되고, 추세와 다음 행동 제안으로 이어집니다." },
      ],
      levelsLabel: "결과 표시 4단계",
      levels: ["좋음", "적절", "주의", "위험"],
      image: "/assets/senio/device-styled.jpg",
      imageAlt: "SENIO 앱 화면: 종합 점수와 당뇨·간기능·신장 기능 항목별 결과",
    },
    products: {
      eyebrow: "Strip + Lens + Care",
      title: "측정부터 관리까지 하나로 연결됩니다.",
      strip: {
        eyebrow: "SENIO Strip",
        title: "소변 7종 지표 스트립",
        body: "채혈 없이, 한 장으로 당뇨·간기능·신장 관련 7종 지표를 확인합니다.",
        indicators: [
          { group: "당뇨", icon: "glucose", items: ["포도당", "케톤"] },
          { group: "간기능", icon: "liver", items: ["빌리루빈", "유로빌리노겐"] },
          { group: "신장", icon: "kidney", items: ["크레아티닌", "미세알부민", "산성도"] },
        ],
      },
      lens: {
        eyebrow: "SENIO Lens",
        title: "광학 측정기",
        body: "사람의 눈이 아니라 광학 센서가 읽습니다. 3분 만에 결과를 확인하고, 좋음·적절·주의·위험 네 단계로 내 상태를 쉽게 이해할 수 있습니다.",
        image: "/assets/senio/device-side.png",
      },
      care: {
        eyebrow: "SENIO Care",
        title: "앱과 기관 대시보드",
        body: "꾸준한 측정으로 내 변화를 확인합니다.",
        image: "/assets/senio/app-mockup.png",
        pills: ["나의 추세", "기관 현황", "보호자 리포트"],
      },
    },
    rnd: {
      eyebrow: "R&D · 실증 현황",
      title: "현장에서 검증하며 만들어가고 있습니다",
      rndEyebrow: "연구개발",
      ipEyebrow: "지식재산",
      verifyEyebrow: "검증",
      verifyBody: "공인시험 성적서 확보 절차를 진행 중이며, 2026년 강원 거점 실증에서 병원 사용 검사 장비와 결과를 비교하는 데이터를 확보할 계획입니다.",
      roadmapEyebrow: "인허가 로드맵",
      roadmapNote: "현재 웰니스 기기로 운영 · 의료기기 인증은 추진 중",
      pilotEyebrow: "현장 실증",
      noticeEyebrow: "이용 안내",
      noticeBody: "현재 SENIO는 웰니스 기기로, 의료 진단이 아닌 일상 모니터링과 이상 징후 확인을 목적으로 합니다. 의료적 판단은 병원 검사를 통해 이루어지며, SENIO는 병원에 가기 전 단계를 담당합니다.",
    },
    orgs: {
      eyebrow: "적용 가능 기관",
      title: "한 사람의 건강부터 지역사회의 건강까지",
      rows: [
        { icon: "building", target: "지자체 · 보건소", usage: "통합돌봄 사업 연계, 지역 주민 예방건강관리" },
        { icon: "care", target: "요양 · 재가복지 기관", usage: "이용자 건강 모니터링, 담당자 업무 효율화, 보호자 소통" },
        { icon: "home", target: "시니어 주거 · 프리미엄 시설", usage: "입주자 건강관리 서비스, 차별화된 케어 제공" },
        { icon: "badge", target: "기업 · 금융기관", usage: "ESG·사회공헌 사업, 시니어 고객 건강 프로그램" },
      ],
      note: "기관 규모와 운영 방식에 따라 도입 구성을 조정할 수 있습니다. 실증 참여나 도입 상담은 아래로 문의해 주세요.",
    },
    cta: {
      eyebrow: "05 · Contact",
      title: "SENIO를 현장에서 확인해 보세요",
      org: {
        eyebrow: "기관 · 기업 도입 문의",
        title: "기관 도입과 실증 참여를 상담해 드립니다",
        body: "2026년 강원 거점 실증에 함께할 기관을 모집하고 있습니다. 기관 규모와 운영 방식에 맞춰 도입 구성을 제안드립니다.",
        ctaLabel: "실증 · 도입 문의",
      },
      personal: {
        eyebrow: "개인 · 보호자",
        title: "SENIO 앱으로 측정 기록과 건강 가이드를 확인하세요",
        screens: ["/assets/senio/app-1.png", "/assets/senio/app-3.png", "/assets/senio/app-4.png"],
        ctaLabel: "앱 출시 안내 받기",
        note: "앱 스토어 링크는 출시와 함께 연결됩니다.",
      },
    },
  },

  impact: {
    meta: {
      title: "IMPACT — 성과와 파트너",
      description: "주요 프로젝트 · 실증 현황 · R&D · 지식재산 · 인증 · 수상 · 선정 사업 · 사회적 가치 · 협력기관 · 연혁",
    },
    header: {
      eyebrow: "Impact & Proof",
      title: "성과",
      lead: "프로젝트, 실증, 연구개발, 인증과 수상, 협력기관과 연혁을 사실 그대로 기록합니다. 성과와 인증은 수치로, 현장의 이야기는 사람 중심으로 전합니다.",
    },
    kpis: [
      { value: "4억+", label: "연구개발 누적 수주", note: "정부 R&D 과제 수행" },
      { value: "7종", label: "한 번에 확인하는 지표", note: "당뇨 · 간기능 · 신장" },
      { value: "4곳", label: "2026 실증 확정 기관", note: "목표 10개 기관" },
      { value: "4곳", label: "MOU 협력기관", note: "지자체 재단 · 요양 · 기업" },
    ],
    partners: [
      { src: "/assets/partners/mou-chuncheon-future.jpg", name: "춘천미래동행재단", kind: "지자체 출연기관" },
      { src: "/assets/partners/mou-chuncheon-hope.jpg", name: "춘천 희망요양원", kind: "요양기관" },
      { src: "/assets/partners/mou-hongcheon-uptown.jpg", name: "업타운㈜", kind: "기업" },
      { src: "/assets/partners/mou-zest.jpg", name: "제스트㈜", kind: "기업" },
    ],
    projects: [
      { src: "/assets/activities/interview-gangwon-elderly.jpg", title: "대한노인회 강원연합회 현장 인터뷰", body: "시니어 건강관리 수요와 현장 운영 조건을 확인하는 사용자 조사" },
      { src: "/assets/activities/interview-wonju-medical.jpg", title: "원주의료사회협동조합 인터뷰", body: "지역 의료·돌봄 기관과의 연계 방안을 논의한 현장 조사" },
      { src: "/assets/activities/interview-udu-center.jpg", title: "우두경로당 이용자 인터뷰", body: "경로당 이용 시니어의 생활 습관과 측정 경험을 듣는 현장 조사" },
      { src: "/assets/activities/governance-meeting.jpg", title: "시니어돌봄거버넌스 협의체 회의", body: "지자체·복지기관·기업이 함께 지역 돌봄 체계를 논의하는 협의체 참여" },
      { src: "/assets/activities/wellness-lecture.jpg", title: "웰니스 특강", body: "기관 이용자와 담당자를 대상으로 한 예방건강관리 교육" },
    ],
    leaderTraining: {
      title: "건강리더 양성",
      body: "맨발걷기 지도자 양성과정을 운영하고, 지역에서 건강 프로그램을 이끌 건강동행리더를 양성합니다. 양성된 리더는 지역 프로그램 운영에 참여합니다.",
      photos: ["/assets/activities/training-1.jpg", "/assets/activities/training-2.jpg"],
    },
    pilots: {
      year: 2026,
      target: 10,
      confirmed: ["춘천 희망요양원", "춘천 희망복지관", "춘천미래동행재단 프로그램", "MG함께자람 사업"],
    },
    rnd: {
      headline: "4억원+",
      summary: "연구개발 누적 수주 4억원 이상",
      body: "중소벤처기업부 디딤돌 R&D, Pre-TIPS, 강원 초기창업 등 정부 R&D 과제를 수행하며 개발을 진행해왔습니다.",
      programs: ["중소벤처기업부 디딤돌 R&D", "Pre-TIPS", "강원 초기창업 지원사업"],
    },
    ip: [
      { label: "핵심 알고리즘 특허", value: "출원 완료", detail: "2026.08.19 · 출원번호 10-2026-0155385" },
      { label: "상표", value: "출원 4건", detail: "" },
      { label: "기기 외관 디자인", value: "출원 1건", detail: "" },
    ],
    ipNote: "특허·상표·디자인은 출원 완료 상태이며, 등록 절차를 진행하고 있습니다.",
    certs: [
      { name: "벤처기업", short: "VENTURE" },
      { name: "소셜벤처기업", short: "SOCIAL VENTURE" },
      { name: "강원도 예비사회적기업", short: "PRE-SOCIAL ENTERPRISE" },
      { name: "여성기업", short: "WOMEN-OWNED" },
    ],
    awards: ["강원지방중소벤처기업청장상", "강원관광재단 이사장상", "강원여성창업 공모전 대상"],
    programs: ["한라대·한림성심대 RISE", "강원 AI헬스케어 글로벌혁신특구", "MG함께자람 사회경제조직육성사업", "강원창업 초기 지원사업"],
    socialValue: [
      { title: "지역사회 예방건강관리", body: "병원에 가기 전 단계의 건강관리를 지역 현장에서 제공해, 시니어의 건강한 자립생활이 더 오래 이어지도록 돕습니다." },
      { title: "돌봄 담당자의 부담 완화", body: "개인별 건강 변화를 기록하고 추적하는 도구를 제공해, 한 사람이 여러 사람을 돌보는 현장의 업무를 덜어냅니다." },
      { title: "지역 건강리더 양성", body: "맨발걷기 지도자와 건강동행리더를 양성해, 지역 주민이 지역의 건강을 이끄는 구조를 만듭니다." },
      { title: "강원 기반 사회적 경제", body: "강원도 예비사회적기업·소셜벤처로서 지역 자원과 원료를 활용하고, 지역 기관과 함께 사업을 설계합니다." },
    ],
    history: [
      {
        year: "2026",
        items: [
          { month: "08", text: "SENIO 핵심 알고리즘 특허 출원 (10-2026-0155385)" },
          { month: "", text: "강원 거점 실증 4개 기관 확정 (연내 10개 기관 목표)" },
          { month: "", text: "공인시험 성적서 확보 절차 진행" },
        ],
      },
      { year: "2027", items: [{ month: "", text: "식약처 의료기기 2등급 인허가 신청 (목표)" }] },
      { year: "2028", items: [{ month: "", text: "의료기기 2등급 인허가 취득 (목표)" }] },
    ],
    roadmap: [
      { period: "현재", title: "웰니스 기기", body: "일상 모니터링과 이상 징후 확인을 목적으로 운영" },
      { period: "2026", title: "실증 · 공인시험", body: "강원 거점 실증에서 병원 사용 검사 장비와 결과 비교 데이터 확보" },
      { period: "2027", title: "인허가 신청", body: "식약처 의료기기 2등급 인허가 신청" },
      { period: "2028", title: "인허가 취득 목표", body: "의료기기 2등급 인허가 취득" },
    ],
    sections: {
      projects: { title: "주요 프로젝트", lead: "현장 조사, 협의체 참여, 교육 등 지역사회와 함께 진행한 활동입니다." },
      pilots: { title: "SENIO 실증 현황", lead: "{year}년 강원 거점 실증에서 병원 사용 검사 장비와 결과를 비교하는 데이터를 확보합니다. 연내 {target}개 기관 실증을 목표로 합니다." },
      rnd: { title: "연구개발과 지식재산" },
      awards: { title: "인증 · 수상 · 선정 사업" },
      social: { title: "사회적 가치", lead: "강원도 예비사회적기업이자 소셜벤처로서, 사업의 성과가 지역사회의 건강으로 이어지도록 설계합니다." },
      partners: { title: "협력기관", lead: "업무협약(MOU)을 체결한 기관과 함께 프로그램 운영과 실증을 진행합니다." },
      history: { title: "연혁", lead: "확정된 이정표와 앞으로의 목표를 연도별로 기록합니다." },
    },
  },

  story: {
    meta: {
      title: "STORY — 맨발걷기 정보 · 힐링로드ON · NEWS",
      description: "현장에서 만드는 건강한 변화. 맨발걷기 정보, 힐링로드ON, NEWS를 한 곳에서 만나보세요.",
    },
    header: {
      eyebrow: "Story",
      title: "스토리",
      lead: "현장에서 만드는 건강한 변화. 맨발걷기 정보, 힐링로드ON 프로그램 소식, 회사 NEWS를 카테고리로 나누어 전합니다.",
    },
    categories: ["맨발걷기 정보", "힐링로드ON", "NEWS"],
    items: [
      {
        slug: "senio-patent-filed",
        category: "NEWS",
        title: "SENIO 핵심 알고리즘 특허 출원을 완료했습니다",
        date: "2026.08.19",
        image: "/assets/senio/device-styled.jpg",
        excerpt: "소변 스트립 판독 편차를 줄이는 핵심 알고리즘에 대해 특허 출원을 완료했습니다. 상표 4건과 기기 외관 디자인 1건도 함께 출원했습니다.",
        body: [
          "㈜위드더레이크는 2026년 8월 19일 SENIO 핵심 알고리즘에 대한 특허 출원을 완료했습니다(출원번호 10-2026-0155385).",
          "이번 출원은 사람의 눈이 아닌 광학 센서로 스트립을 읽어 판독 편차를 줄이는 방식에 관한 것입니다. 상표 출원 4건과 기기 외관 디자인 출원 1건도 함께 진행했습니다.",
          "SENIO는 현재 웰니스 기기로 운영하고 있으며, 공인시험 성적서 확보 절차와 강원 거점 실증을 거쳐 2027년 식약처 의료기기 2등급 인허가 신청을 준비하고 있습니다.",
        ],
        featured: true,
      },
      {
        slug: "barefoot-leader-course",
        category: "힐링로드ON",
        title: "맨발걷기 지도자 양성과정, 현장의 건강리더를 키웁니다",
        date: "2026.06.20",
        image: "/assets/activities/training-1.jpg",
        excerpt: "지역에서 걷기 프로그램을 직접 이끌 지도자를 양성하는 과정입니다. 이론 교육과 현장 실습을 함께 진행합니다.",
        body: [
          "맨발걷기 지도자 양성과정은 지역에서 걷기 프로그램을 직접 운영할 건강리더를 양성하는 교육입니다.",
          "걷기의 기본 원리와 안전 수칙, 시니어 대상 프로그램 운영 방법을 배우고, 현장 실습을 통해 실제 진행 경험을 쌓습니다.",
          "과정을 수료한 지도자는 지자체·복지기관과 함께하는 COMMUNITY HEALTH 프로그램에 참여합니다.",
        ],
        featured: true,
      },
      {
        slug: "chuncheon-future-mou",
        category: "NEWS",
        title: "춘천미래동행재단과 지역사회 예방건강관리 협약을 맺었습니다",
        date: "2026.05.12",
        image: "/assets/partners/mou-chuncheon-future.jpg",
        excerpt: "재단 프로그램과 연계해 지역 주민 대상 예방건강관리 프로그램과 SENIO 실증을 함께 진행합니다.",
        body: [
          "㈜위드더레이크는 춘천미래동행재단과 지역사회 예방건강관리 업무협약을 체결했습니다.",
          "양 기관은 재단이 운영하는 지역 프로그램에 걷기·생활습관 프로그램을 연계하고, SENIO를 활용한 건강 모니터링 실증을 함께 진행합니다.",
        ],
        featured: true,
      },
      {
        slug: "why-barefoot-walking",
        category: "맨발걷기 정보",
        title: "맨발걷기, 지역사회와 함께 걷는 이유",
        date: "2026.04.03",
        image: "/assets/activities/barefoot-1.jpg",
        excerpt: "위드더레이크는 함께 걷는 현장에서 시작했습니다. 걷기가 예방건강관리의 출발점이 되는 이유를 정리했습니다.",
        body: [
          "걷기는 특별한 장비 없이 누구나 시작할 수 있는 건강행동입니다. 맨발로 흙길을 걷는 경험은 걷기를 습관으로 이어가게 하는 계기가 됩니다.",
          "위드더레이크는 지역 주민이 함께 걷는 프로그램에서 출발했고, 걷기를 측정·이해·행동·지속·변화 확인의 순환으로 연결하는 구조를 만들어가고 있습니다.",
        ],
      },
      {
        slug: "daily-walking-habit",
        category: "맨발걷기 정보",
        title: "일상 속 걷기 습관 만들기",
        date: "2026.03.14",
        image: "/assets/activities/barefoot-3.jpg",
        excerpt: "무리하지 않고 오래 이어가는 걷기 루틴을 만드는 방법을 안내합니다.",
        body: [
          "걷기는 강도보다 지속이 중요합니다. 하루 10분부터 시작해 기록을 남기고, 변화를 확인하는 것이 습관을 유지하는 방법입니다.",
          "SENIO 앱은 걷기 기록과 측정 결과를 함께 보여 주어, 걷기가 몸의 변화로 이어지는지를 확인할 수 있게 돕습니다.",
        ],
      },
      {
        slug: "wellness-lecture",
        category: "NEWS",
        title: "웰니스 특강, 건강한 습관을 나누다",
        date: "2026.02.27",
        image: "/assets/activities/wellness-lecture.jpg",
        excerpt: "기관 이용자와 담당자를 대상으로 예방건강관리 특강을 진행했습니다.",
        body: ["지역 기관 이용자와 담당자를 대상으로 웰니스 특강을 진행했습니다. 걷기·생활습관·마음건강을 주제로 일상에서 실천할 수 있는 방법을 나눴습니다."],
      },
      {
        slug: "governance-meeting",
        category: "NEWS",
        title: "시니어돌봄거버넌스 협의체 회의에 참여했습니다",
        date: "2026.01.22",
        image: "/assets/activities/governance-meeting.jpg",
        excerpt: "지자체·복지기관·기업이 함께 지역 돌봄 체계를 논의하는 협의체에 참여했습니다.",
        body: ["시니어돌봄거버넌스 협의체 회의에 참여해 지역 돌봄 체계 안에서 예방건강관리와 SENIO의 역할을 논의했습니다."],
      },
    ],
  },

  store: {
    meta: {
      title: "STORE — WITH WELL ME 마켓",
      description: "맨발걷기와 셀프케어를 위한 WITH WELL ME 제품을 네이버 스마트스토어에서 만나보세요.",
    },
    header: {
      eyebrow: "Store",
      title: "스토어",
      lead: "맨발걷기와 셀프케어를 위한 제품. 위드웰미 풋케어, 어싱 제품, 힐링로드ON 걷기 체험을 네이버 스마트스토어에서 구매하실 수 있습니다. 제품을 누르면 스마트스토어 상품 페이지로 이동합니다.",
      ctaLabel: "네이버 스마트스토어 방문하기",
      brandCtaLabel: "브랜드 소개 보기",
    },
    categories: ["케어", "어싱", "체험"],
    products: [
      {
        brand: "위드웰미",
        name: "데일리 파워 쿨링 미스트 100ml",
        price: 37800,
        originalPrice: 42000,
        category: "케어",
        badge: "베스트",
        image: "/assets/store/withwellme_powercoolingmist.jpg",
        url: "https://smartstore.naver.com/withlab201/products/12254246304",
        axis: "CARE",
      },
      {
        brand: "위드웰미",
        name: "데일리 풋샴푸 풋워시 200ml",
        price: 17820,
        originalPrice: 19800,
        category: "케어",
        badge: "인기",
        image: "/assets/store/withwellme_dailyfootwash.jpg",
        url: "https://smartstore.naver.com/withlab201/products/12248115925",
        axis: "CARE",
      },
      {
        brand: "숨토프랜드",
        name: "어싱 패드 접지 매트 (슈퍼싱글 · 퀸)",
        price: 270000,
        category: "어싱",
        image: "/assets/store/soomtofriend_earthingpad.jpg",
        url: "https://smartstore.naver.com/withlab201/products/12362102946",
        axis: "RECOVER",
      },
      {
        brand: "숨토프랜드",
        name: "접지 어싱 베개 커버 60×70cm",
        price: 60000,
        category: "어싱",
        badge: "추천",
        image: "/assets/store/soomtofriend_earthingcover.jpg",
        url: "https://smartstore.naver.com/withlab201/products/12314861939",
        axis: "RECOVER",
      },
      {
        brand: "힐링로드ON",
        name: "태백 웰니스 걷기 투어 (당일형)",
        price: 10000,
        category: "체험",
        image: "/assets/store/withwellme_logo1.jpeg",
        url: "https://smartstore.naver.com/withlab201/products/12679438666",
        axis: "WALK",
      },
    ],
    brand: {
      logo: "/assets/logo/with-well-me.png",
      lead: "EAT · MOVE · WALK · CARE · RECOVER — 하루의 리듬을 따라 건강한 행동을 일상으로 잇는 제품과 콘텐츠를 만듭니다.",
      body: "단체 구매나 제품 관련 문의는 CONTACT US에서 ‘제품·구매’ 유형을 선택해 남겨 주세요.",
      ctaLabel: "제품·구매 문의",
      image: "/assets/stock/barefoot-trail.jpg",
      imageAlt: "숲길을 맨발로 걷는 모습",
    },
  },

  contact: {
    meta: {
      title: "CONTACT US — 문의",
      description: "사업·협력, SENIO 실증·도입, 프로그램 운영, 제품·구매 문의를 남겨주세요.",
    },
    header: {
      eyebrow: "Contact Us",
      title: "문의하기",
      lead: "문의를 남겨주시면 담당자가 확인 후 연락드립니다. 문의 유형을 선택하고 요청 내용을 남겨 주세요. 접수 후 영업일 기준 2~3일 안에 답변드립니다.",
    },
    types: [
      { label: "사업·협력", desc: "지자체·기관·기업과의 협력, 공동사업 제안" },
      { label: "SENIO 실증·도입", desc: "2026 실증 참여, 기관 도입 상담" },
      { label: "프로그램 운영", desc: "걷기·운동·노쇠 예방·생활습관·마음건강 프로그램" },
      { label: "제품·구매", desc: "WITH WELL ME 제품, 단체 구매" },
    ],
    directLabel: "직접 연락",
    form: {
      inquiryTypes: ["사업·협력", "SENIO 실증·도입", "프로그램 운영", "제품·구매", "기타"],
      placeholder: "기관 유형, 이용자 규모, 희망 일정 등을 함께 적어 주시면 상담이 빨라집니다.",
      successTitle: "문의가 접수되었습니다",
      successBody: "보내주신 내용을 확인한 뒤 담당자가 순차적으로 연락드리겠습니다.",
    },
  },

  privacy: {
    meta: { title: "개인정보 처리방침", description: "㈜위드더레이크 개인정보 처리방침" },
    header: {
      eyebrow: "Privacy Policy",
      title: "개인정보 처리방침",
      lead: "㈜위드더레이크가 수집하는 개인정보의 항목, 목적, 보유 기간과 이용자의 권리를 안내합니다.",
    },
    sections: [
      {
        title: "1. 수집하는 개인정보 항목",
        body: [
          "㈜위드더레이크는 CONTACT US 문의 접수를 위해 다음 항목을 수집합니다.",
          "필수: 회사명, 담당자 이름, 연락처, 이메일, 문의 유형, 요청 내용",
          "선택: 부서, 직책",
        ],
      },
      {
        title: "2. 개인정보의 수집 및 이용 목적",
        body: ["수집한 개인정보는 문의 확인 및 답변, 사업·협력 상담, SENIO 실증·도입 상담, 프로그램 운영 상담, 제품·구매 안내 목적으로만 이용합니다."],
      },
      {
        title: "3. 개인정보의 보유 및 이용 기간",
        body: ["문의 처리가 완료된 이후 관련 법령에 따른 보관 의무가 없는 한 지체 없이 파기합니다. 전자적 파일은 복구할 수 없는 방법으로 삭제합니다."],
      },
      {
        title: "4. 개인정보의 제3자 제공 및 처리 위탁",
        body: [
          "㈜위드더레이크는 이용자의 개인정보를 원칙적으로 외부에 제공하지 않으며, 법령에 근거가 있거나 이용자가 사전에 동의한 경우에만 제공합니다.",
          "문의 접수 메일 발송을 위해 이메일 발송 서비스에 처리를 위탁할 수 있으며, 위탁 시 수탁자와 업무 내용을 본 방침에 공개합니다.",
        ],
      },
      {
        title: "5. 이용자의 권리",
        body: ["이용자는 언제든지 자신의 개인정보에 대한 열람, 정정, 삭제, 처리정지를 요청할 수 있으며, 아래 문의처로 연락하시면 지체 없이 조치합니다."],
      },
      {
        title: "6. 개인정보 보호책임자 및 문의처",
        body: ["{company} {team} {person} · 전화 {phone} · 이메일 {email}"],
      },
      {
        title: "7. 고지",
        body: ["본 방침은 시행일부터 적용되며, 내용이 변경될 경우 홈페이지를 통해 공지합니다."],
      },
    ],
  },

  info: {
    meta: {
      title: "맨발걷기 정보 — 맨발걷기의 모든 것",
      description: "맨발걷기(어싱·그라운딩)란 무엇인지, 과학적으로 보고된 효과, 올바른 방법과 주의사항, 관련 연구 자료를 정리했습니다.",
    },
    header: {
      eyebrow: "Earthing / Grounding",
      title: "맨발걷기의 모든 것",
      lead: "땅과 연결되어 자연의 에너지를 느끼는 가장 원초적이고 효과적인 건강법. 맨발걷기의 원리와 효과, 안전하게 시작하는 방법을 안내합니다.",
    },
    what: {
      eyebrow: "What is Barefoot Walking?",
      title: "맨발걷기란?",
      body: [
        "맨발걷기(Earthing / Grounding)는 신발 없이 흙, 잔디, 모래 같은 자연 표면을 걷는 활동입니다. 발바닥의 감각 수용체를 직접 자극해 근력 · 균형 · 보행 메커니즘을 개선할 수 있다는 연구가 있습니다.",
        "인체가 지구의 자연 전하와 직접 연결됨으로써 다양한 건강 효과를 얻을 수 있으며, 현대인이 신발과 건물로 인해 잃어버린 땅과의 연결을 회복하는 방법입니다.",
      ],
      linkLabel: "National Geographic 기사 보기",
      linkUrl: "https://www.nationalgeographic.com/science/article/why-walking-barefoot-can-actually-help-your-feet",
    },
    benefits: {
      eyebrow: "Scientific Benefits",
      title: "과학적으로 보고된 효과",
      lead: "다양한 연구에서 맨발걷기의 긍정적 효과가 보고되고 있습니다. 아래 내용은 연구 결과를 요약한 것이며, 개인에 따라 효과가 다를 수 있습니다.",
      items: [
        { title: "발·다리 근력 강화", body: "구속 없는 움직임과 감각 자극이 발 근육과 균형성 개선에 도움을 줍니다.", source: "National Geographic", url: "https://www.nationalgeographic.com/science/article/why-walking-barefoot-can-actually-help-your-feet" },
        { title: "인지 기능 향상", body: "12주간 맨발걷기 후 인지 속도 및 집중력 향상, 뇌 스트레스 감소가 관찰되었습니다.", source: "PubMed 연구", url: "https://pubmed.ncbi.nlm.nih.gov/38118297/" },
        { title: "스트레스·수면 개선", body: "스트레스 감소, 수면 질 향상, 삶의 질 개선 효과가 연구에서 보고되었습니다.", source: "PubMed 연구", url: "https://pubmed.ncbi.nlm.nih.gov/41302225/" },
        { title: "염증·면역 반응", body: "맨발걷기 후 염증 지표 변화, 면역 관련 물질 반응이 관찰되었습니다.", source: "MDPI 학술지", url: "https://www.mdpi.com/2227-9032/12/23/2372" },
      ],
    },
    method: {
      eyebrow: "How to Practice",
      title: "올바른 맨발걷기 방법",
      steps: [
        { emoji: "🌿", title: "장소 선택", body: "흙, 잔디, 모래 등 자연 바닥이 좋습니다. 유리 조각이나 날카로운 물체가 없는 안전한 장소를 선택하세요." },
        { emoji: "⏱️", title: "점진적 적응", body: "처음에는 5~10분 정도로 짧게 시작하여 점차 시간을 늘려가세요. 전문가들은 점진적 적응을 권장합니다." },
        { emoji: "🧘", title: "자세와 호흡", body: "허리를 곧게 펴고, 발 전체로 땅을 딛듯이 걸으세요. 깊은 호흡을 하며 자연의 소리와 향기를 느껴보세요." },
        { emoji: "✨", title: "마무리 관리", body: "걷기가 끝나면 발을 깨끗이 씻고 보습제를 발라주세요. 발바닥에 상처가 있는지 확인하고 관리해 주세요." },
      ],
    },
    safety: {
      eyebrow: "Safety First",
      title: "주의사항",
      items: [
        { title: "당뇨병 환자", body: "발에 감각이 둔한 경우 상처를 인지하지 못할 수 있으니 의사와 상담 후 진행하세요." },
        { title: "극단적 날씨", body: "너무 뜨겁거나 차가운 바닥은 피하세요. 화상이나 동상의 위험이 있습니다." },
        { title: "상처·감염 위험", body: "발에 상처가 있으면 감염 위험이 있으니 완치 후 맨발걷기를 하세요." },
        { title: "의료 대체 불가", body: "맨발걷기는 질병 치료를 대체할 수 없습니다. 건강 문제가 있으면 전문의와 상담하세요." },
      ],
      disclaimer: "※ 이 페이지의 정보는 의학적 조언이 아닙니다. 개인의 건강 상태에 따라 전문가와 상담하시기 바랍니다.",
    },
    research: {
      eyebrow: "Research & Articles",
      title: "관련 연구 자료",
      lead: "맨발걷기와 어싱(Earthing)에 대한 과학적 연구와 신뢰할 수 있는 매체의 기사입니다.",
      items: [
        { tag: "발 건강·근력", title: "Why walking barefoot can actually help your feet", body: "맨발걷기가 발 근력 개선, 균형감 향상, 걷기 패턴 개선에 도움이 된다는 연구 결과 소개", source: "National Geographic", url: "https://www.nationalgeographic.com/science/article/why-walking-barefoot-can-actually-help-your-feet" },
        { tag: "뇌 기능·인지", title: "Barefoot walking improves cognitive ability in adolescents", body: "12주간 맨발걷기 운동 후 인지 속도 및 집중력 향상, 뇌 스트레스 감소 관찰", source: "PubMed (임상연구)", url: "https://pubmed.ncbi.nlm.nih.gov/38118297/" },
        { tag: "통증 관리", title: "Barefoot walking is beneficial for plantar heel pain", body: "발바닥 통증 환자에서 맨발걷기 그룹이 통증 완화, 기능 개선, 삶의 질 향상을 보임", source: "PubMed (RCT 연구)", url: "https://pubmed.ncbi.nlm.nih.gov/38926837/" },
        { tag: "웰니스·수면", title: "Effects of Barefoot Walking on Menopausal Symptoms", body: "중년 여성에서 폐경기 증상 완화, 스트레스 감소, 수면 질 향상 효과 관찰", source: "PubMed (임상연구)", url: "https://pubmed.ncbi.nlm.nih.gov/41302225/" },
        { tag: "면역·생리", title: "Effects of Barefoot Walking on CRP, IFNγ, and Serotonin", body: "숲속 맨발걷기 후 염증 지표, 면역 관련 물질, 세로토닌 수치 변화 관찰", source: "MDPI (학술지)", url: "https://www.mdpi.com/2227-9032/12/23/2372" },
        { tag: "염증·자가면역", title: "Grounding and inflammation research", body: "접지(Grounding)가 염증, 면역 반응, 상처 치유에 미치는 영향에 대한 통합 리뷰", source: "PMC (NIH)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4378297/" },
      ],
      moreLabel: "맨발걷기 관련 뉴스 더보기",
      moreUrl: "/story?category=맨발걷기 정보",
    },
    cta: {
      title: "지금 맨발걷기를 시작해보세요",
      body: "힐링로드 ON과 함께 전문 가이드 음성을 들으며 안전하고 효과적인 맨발걷기를 경험하세요.",
      buttonLabel: "힐링로드 ON 시작하기",
      buttonUrl: "/healing",
    },
  },

  healing: {
    meta: {
      title: "힐링로드 ON — 맨발걷기 워킹 테라피",
      description: "걷기 안내와 긍정확언 음성을 들으며 걷고, 전국의 맨발 산책로를 찾고, 오늘의 감정을 기록하는 맨발걷기 워킹 테라피 서비스입니다.",
    },
    header: {
      eyebrow: "Healing Road ON",
      title: "힐링로드 ON",
      lead: "맨발걷기 워킹 테라피. 걷기 안내와 긍정확언 음성을 들으며 걷고, 길 안내로 산책로를 찾고, 걷고 난 뒤 오늘의 감정을 기록하세요.",
    },
    features: [
      { emoji: "🎧", title: "오디오 듣기", body: "걷기 안내와 긍정적 메시지", anchor: "audio" },
      { emoji: "🗺️", title: "길 안내", body: "전국의 힐링 산책로를 찾아보세요", anchor: "trails" },
      { emoji: "📝", title: "기록하기", body: "오늘의 감정을 기록해요", anchor: "record" },
      { emoji: "📋", title: "설문조사", body: "서비스 개선에 참여해주세요", anchor: "survey" },
    ],
    audio: {
      eyebrow: "Audio Guide",
      title: "오디오 듣기",
      lead: "원하는 카테고리를 선택하고 재생 버튼을 누르세요. 이어폰을 끼고 걸으면 더 좋습니다.",
      walkGuides: {
        label: "걷기 안내",
        description: "걷기의 효과와 올바른 방법을 안내해드려요",
        items: [
          { emoji: "🚶‍♀️", title: "걷기 시작하기", description: "걷기의 의미와 효과, 호흡과 스트레칭, 걷기 명상 안내", src: wav("1.걷기안내.wav") },
          { emoji: "🚶‍♂️", title: "맨발걷기 안내", description: "맨발걷기의 효과와 안전한 맨발걷기 가이드", src: wav("2.맨발걷기안내.wav") },
          { emoji: "😄", title: "걷기 마무리하기", description: "힐링로드 ON을 이용해 주셔서 감사합니다. 기록과 설문 안내", src: wav("(기록_설문안내).wav") },
        ],
      },
      affirmations: {
        label: "긍정확언",
        description: "마음을 다독이는 따뜻한 메시지",
        items: [
          { emoji: "🌳", title: "자기수용 1", description: "나는 있는 그대로의 나를 사랑하고 존중합니다.", src: wav("1.나는있는그대로의 나를 사랑하고 존중합니다.wav") },
          { emoji: "🌳", title: "자기수용 2", description: "나의 모든 경험은 나를 성장시키는 소중한 자산입니다.", src: wav("2. 나의 모든경험은 나르 성장시키는 소중한 자산입니다.wav") },
          { emoji: "🌱", title: "성장 1", description: "나는 매일 새로운 가능성을 향해 나아갑니다.", src: wav("1.나는 매일 새로운 가능성을 향해 나아갑니다..wav") },
          { emoji: "🌱", title: "성장 2", description: "나는 모든 경험에서 배우고 성장합니다.", src: wav("2.나는 모든 경험에서 배우고 성장합니다..wav") },
          { emoji: "🏖", title: "자신감 1", description: "나는 나의 진정한 목소리를 당당하게 표현합니다.", src: wav("1.나는 나의 진정한 목소리를 당당하게 표현합니다.wav") },
          { emoji: "🏖", title: "자신감 2", description: "나는 나의 강점과 재능을 온전히 발휘합니다.", src: wav("2. 나는 나의 강점과 재능을 온전히 발휘합니다.wav") },
          { emoji: "🌫", title: "평화 1", description: "나는 나의 마음에 평화와 고요함을 초대합니다.", src: wav("1. 나는 나의 마음에 평화와 고요함을 초대합니다.wav") },
          { emoji: "🌫", title: "평화 2", description: "나는 지금 이 순간에 온전히 머무르며, 나 자신을 치유합니다.", src: wav("2. 나는 지금 이 순간에 온전히 머무르며, 나 자신을 치유합니다.wav") },
          { emoji: "⛅", title: "감사", description: "나는 나의 삶에 주어진 모든 것에 감사합니다.", src: wav("1.나는 나의 삶에 주어진 모든 것에 감사합니다.wav") },
        ],
      },
      trailGuides: {
        label: "길 안내",
        description: "전국의 힐링 산책로를 찾아보세요",
        items: [
          { emoji: "🌳", title: "화강 느티나무 삼십리길", description: "강원도 철원군 화강 느티나무 삼십리길 맨발걷기 코스 안내", region: "강원 철원", distance: "3.0km", walkingTime: "약 50분", difficulty: "보통", src: wav("3.길안내_1_화강 느티나무 삼십리길.wav") },
          { emoji: "🌲", title: "군탄공원 맨발걷기길", description: "강원도 철원군 군탄공원 및 맨발걷기길 코스 안내", region: "강원 철원", distance: "2.5km", walkingTime: "약 40분", difficulty: "쉬움", src: wav("3.길안내_2_군탄공원맨발걷기길.wav") },
          { emoji: "🌱", title: "춘천 공지천 산책로", description: "강원도 춘천시 공지천, 공지천 산책로, 봄내맨발로 길 안내", region: "강원 춘천", distance: "", walkingTime: "", difficulty: "쉬움", src: wav("_20250905.wav") },
          { emoji: "🌲", title: "태백 지지리골 맨발걷기숲길", description: "태백 체험공원, 지지리골 맨발걷기숲길, 지지리골 자작나무숲 안내", region: "강원 태백", distance: "", walkingTime: "", difficulty: "보통", src: wav("_20251004.wav") },
          { emoji: "🏛️", title: "경주 대릉원", description: "경주 대릉원(사적 제512호) 걷기 길 안내", region: "경북 경주", distance: "", walkingTime: "", difficulty: "쉬움", src: wav(" 대릉원 (20251107).wav") },
          { emoji: "🌾", title: "경주 봉황대", description: "경주 노동동 봉황대 걷기길 안내", region: "경북 경주", distance: "", walkingTime: "", difficulty: "쉬움", src: wav(" 봉황대(20251107).wav") },
          { emoji: "🏘️", title: "경주 황리단길", description: "경주 황남동 포석로 일대 황리단길 안내", region: "경북 경주", distance: "", walkingTime: "", difficulty: "쉬움", src: wav("(20251107).wav") },
          { emoji: "🔭", title: "경주 첨성대", description: "경주 첨성대, 반월성, 계림 맨발걷기 길 안내", region: "경북 경주", distance: "", walkingTime: "", difficulty: "쉬움", src: wav(" 첨성대(20251107).wav") },
          { emoji: "🌊", title: "경주 보문단지", description: "경주 보문단지, 보문호 안내", region: "경북 경주", distance: "", walkingTime: "", difficulty: "쉬움", src: wav(" 보문단지(20251107).wav") },
          { emoji: "🏞️", title: "소양강 맨발 산책로", description: "춘천시 소양강을 따라 걷는 평화로운 맨발 코스", region: "강원 춘천", distance: "2.5km", walkingTime: "약 40분", difficulty: "쉬움", src: "" },
          { emoji: "🏖️", title: "경포해변 맨발 워킹", description: "강릉시 경포해변의 모래사장을 걷는 해변 코스", region: "강원 강릉", distance: "2.8km", walkingTime: "약 45분", difficulty: "쉬움", src: "" },
        ],
      },
    },
    trails: {
      eyebrow: "Healing Trails",
      title: "길 안내",
      lead: "힐링로드 ON이 소개하는 맨발 산책로입니다. 코스마다 안내 음성을 들을 수 있습니다.",
    },
    record: {
      eyebrow: "Daily Record",
      title: "기록하기",
      lead: "걷기 후 느낀 감정을 기록해요. 기록은 이 기기의 브라우저에만 저장됩니다.",
      moods: [
        { emoji: "😊", label: "행복해요" },
        { emoji: "😌", label: "편안해요" },
        { emoji: "💪", label: "활기차요" },
        { emoji: "😐", label: "그저 그래요" },
        { emoji: "😔", label: "우울해요" },
        { emoji: "😫", label: "힘들어요" },
      ],
      note: "오늘의 감정을 고르고 한 줄 메모를 남겨 보세요. 최근 기록 7개가 아래에 표시됩니다.",
    },
    survey: {
      title: "설문조사",
      body: "서비스 개선에 참여해주세요. 2~3분이면 충분합니다.",
      buttonLabel: "설문 참여하기",
      url: "https://forms.gle/At8WaVZLsXLCoxCLA",
    },
    store: {
      title: "힐링로드 ON 제품",
      body: "맨발걷기에 필요한 제품을 네이버 스마트스토어에서 만나보세요.",
      buttonLabel: "스마트스토어 바로가기",
    },
    community: {
      title: "힐링로드 ON 커뮤니티",
      body: "함께 걷는 사람들의 이야기와 산책로 정보를 네이버 카페에서 나눕니다.",
      buttonLabel: "네이버 카페 가기",
    },
  },
};
